# Setup
title: Jekyll Test
#url: "http://gymnasium.github.io/cms/"
baseurl: /jekyll  # This makes the index page URL localhost:4000/cms/ Remember: Omit the trailing slash!

# collections:
#     events:
#         output: true
#         permalink: /cms/events/


# Custom vars

# version:             1.0.0

# Conversion
kramdown:
  input: GFM
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
# detach:  false
# port:    4000
# host:    127.0.0.1
# baseurl: / # does not include hostname
# show_dir_listing: false

repository: <andrewpmiller>/<jekyll-test
